apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: fpshqnjv8-nodejs-gitops
  description: This is GitOps manifest for fpshqnjv8-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=fpshqnjv8-nodejs
    backstage.io/kubernetes-id: fpshqnjv8-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: fpshqnjv8-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:fpshqnjv8-nodejs
